#:schema https://json.schemastore.org/rustfmt.json

edition = "2021"

unstable_features = true

condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
imports_layout = "Mixed"
max_width = 100
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
single_line_if_else_max_width = 0
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
