#:schema https://json.schemastore.org/cargo-make.json
# Documentation: https://github.com/sagiegurari/cargo-make

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_BACKTRACE = "1"

[config]
load_cargo_aliases = true

# https://github.com/rust-lang/rust-clippy
[tasks.pre-clippy]
category = "hooks"
description = "Run tasks before the `lint`"
install_crate = { rustup_component_name = "clippy" }
command = "cargo"
args = ["clippy", "--version"]
[tasks.clippy]
category = "lint"
description = "Run clippy analysis on the Rust codebase"
command = "cargo"
args = ["clippy", "--all-targets", "--no-deps"]
dependencies = ["pre-clippy"]
[tasks.clippy-fix]
category = "fix"
description = "Attempt to auto-fix Clippy issues"
command = "cargo"
args = ["clippy", "--all-targets", "--no-deps", "--fix"]

# https://github.com/rust-lang/rustfmt
[tasks.pre-format]
category = "hooks"
description = "Run tasks before the `format`"
install_crate = { rustup_component_name = "rustfmt" }
command = "cargo"
args = ["fmt", "--version"]
[tasks.format]
category = "lint"
description = "Check format of the Rust code with `rustfmt`"
command = "cargo"
args = ["fmt", "--check"]
dependencies = ["pre-format"]
[tasks.format-fix]
category = "lint"
description = "Attempt to auto-fix format rustmft issues"
command = "cargo"
args = ["fmt", "--verbose"]
dependencies = ["pre-format"]

# https://github.com/nextest-rs/nextest
[tasks.pre-test]
category = "hooks"
description = "Run tasks before the `test`"
install_crate = "cargo-nextest"
command = "cargo"
args = ["nextest", "--version"]
[tasks.test]
category = "test"
description = "Run crate tests with `nextest`"
command = "cargo"
args = ["nextest", "run", "--all-features", "--no-fail-fast"]
dependencies = ["pre-test"]

# https://github.com/crate-ci/typos
[tasks.pre-typos]
workspace = false
category = "hooks"
description = "Run tasks before the `typos`"
install_crate = "typos-cli"
command = "typos"
args = ["--version"]
[tasks.typos]
workspace = false
category = "lint"
description = "Find typos in the code"
command = "typos"
args = ["--verbose"]
dependencies = ["pre-typos"]
[tasks.typos-fix]
workspace = false
category = "fix"
description = "Attempt to auto-fix typos issues"
extend = "typos"
args = ["--verbose", "--write-changes"]
