#:schema https://json.schemastore.org/rustfmt.json

unstable_features = true

chain_width = 30
condense_wildcard_suffixes = true
hard_tabs = true
imports_granularity = "Crate"
imports_layout = "Mixed"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
max_width = 100
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
normalize_comments = true
normalize_doc_attributes = true
format_macro_matchers = true
single_line_if_else_max_width = 0
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
