# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: CI
# NOTE: CI -> Continuous Integration

on:
    pull_request:
        branches: [main]
        types: [opened, reopened, ready_for_review, synchronize]
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            reason:
                description: Reason of re-running this workflow
                required: false
                type: string

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    CI: true
    CARGO_TERM_COLOR: always

jobs:
    lint-clippy:
        name: Lint / Clippy
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                toolchain: [stable, nightly]
        steps:
            - name: Checkout to the repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v4

            - name: Setup Rust
              # https://github.com/actions-rs/toolchain
              uses: actions-rs/toolchain@v1
              with:
                  components: clippy
                  override: true
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}

            - name: Setup the cache
              # https://github.com/Swatinem/rust-cache
              uses: Swatinem/rust-cache@v2

            - name: Lint Rust codebase with Clippy
              # https://github.com/actions-rs/clippy-check
              uses: actions-rs/clippy-check@v1
              with:
                  args: --all-targets --no-deps --all-features
                  toolchain: ${{ matrix.toolchain }}
                  token: ${{ secrets.GITHUB_TOKEN }}

    lint-typos:
        name: Lint / typos
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to the repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v4

            - name: Spell check with `typos`
              # https://github.com/crate-ci/typos
              uses: crate-ci/typos@v1.16.22
