# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Clippy

on:
    workflow_call:
    workflow_dispatch:
        inputs:
            args:
                description: Clippy command args to pass
                default: --all-targets --no-deps --all-features
                required: false
                type: string
            toolchain:
                description: Rust toolchain to use
                required: true
                type: string

defaults:
    run:
        shell: bash

env:
    CI: true
    CARGO_TERM_COLOR: always

permissions:
    pull-requests: write

jobs:
    lint_clippy:
        name: Clippy
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - name: Checkout to the repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v4

            - name: Setup Rust
              # https://github.com/dtolnay/rust-toolchain
              uses: dtolnay/rust-toolchain@v1
              with:
                  components: clippy
                  toolchain: ${{ inputs.toolchain }}

            - name: Setup the cache
              # https://github.com/Swatinem/rust-cache
              uses: Swatinem/rust-cache@v2

            - name: Check Rust codebase with Clippy
              # https://github.com/actions-rs/clippy-check
              uses: actions-rs/clippy-check@v1
              id: lint_clippy
              with:
                  args: ${{ inputs.args }}
                  toolchain: ${{ inputs.toolchain }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create error comment
              if: always() && (steps.lint_clippy.outputs.error_message != null)
              # https://github.com/marocchino/sticky-pull-request-comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: lint-clippy-error
                  message: |
                      ## ❌ **Clippy**

                      **There are some issues found in the Rust codebase!**

                      You can preview the annotations in [Files changed] tab, or you can see the details below.

                      [Files changed]: https://github.com/rust-cleaners/polished-css/pull/${{ github.event.pull_request.number }}/files

                      <details>
                        <summary>Error messages details</summary>

                        ```
                        ${{ steps.lint_clippy.outputs.error_message }}
                        ```

                      </details>

                      ---

                      > **Note:**
                      > This comment will automatically get deleted once the issue is resolved.

            - name: Delete the error comment
              # Delete a previous comment when the issue has been resolved
              if: ${{ steps.lint_clippy.outputs.error_message == null }}
              # https://github.com/marocchino/sticky-pull-request-comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: pr-title-lint-error
                  delete: true
