# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: nextest

on:
    workflow_call:
        inputs:
            toolchain:
                description: Rust toolchain channel to use
                type: string
                required: false
                default: nightly
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    CI: true
    CARGO_TERM_COLOR: always

permissions:
    pull-requests: write

jobs:
    nextest:
        name: nextest
        outputs:
            status: ${{ steps.failure.outputs.status || steps.success.outputs.status }}
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - name: Checkout to the repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v4

            # FIXME: Delete this if the solution works
            # - name: Setup Rust
            #   # https://github.com/moonrepo/setup-rust
            #   uses: moonrepo/setup-rust@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #       bins: cargo-nextest
            #       cache: true
            #       channel: ${{ inputs.toolchain }}
            #       profile: minimal
            - name: Setup Rust
              # https://github.com/dtolnay/rust-toolchain
              uses: dtolnay/rust-toolchain@stable
              id: toolchain
              with:
                  components: ""
                  toolchain: ${{ inputs.toolchain }}

            - name: Install cargo extensions binaries
              # https://github.com/taiki-e/install-action
              uses: taiki-e/install-action@v2
              with:
                  tool: cargo-nextest

            - name: Setup the cache
              # https://github.com/Swatinem/rust-cache
              uses: Swatinem/rust-cache@v2
              with:
                  key: ${{ inputs.toolchain }}-${{ steps.toolchain.outputs.cachekey }}-nextest

            - name: Run tests with latest nextest release
              run: cargo nextest run --all-features --profile ci

            - run: echo "status=failure" >> $GITHUB_OUTPUT
              id: failure
              if: failure()
            - run: echo "status=success" >> $GITHUB_OUTPUT
              id: success
              if: success()

    error-comment:
        uses: ./.github/workflows/error-comment.yml
        needs: [nextest]
        if: always()
        with:
            step_status: ${{ needs.nextest.outputs.status }}
            header: test-nextest-error-${{ inputs.toolchain }}
            message: |
                ## ❌ **nextest**

                Some of the test(s) has failed on the toolchain channel: **${{ inputs.toolchain }}**
