# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: PR maintenance

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

permissions:
    pull-requests: write

jobs:
    pr_title:
        name: Validate the Pull Request title
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: Check if the Pull Request title is semantic
              id: lint_pr_title
              # https://github.com/amannn/action-semantic-pull-request
              uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Output the previous step status
              run: |
                  STATUS=${{ steps.lint_pr_title.outputs.status }}
                  ERROR_MESSAGE=${{ steps.lint_pr_title.outputs.error_message }}
                  echo "::set-output name=status::$STATUS"
                  echo "::set-output name=error_message::$ERROR_MESSAGE"

    error-comment:
        uses: ./.github/workflows/error-comment.yml
        needs: [pr-title]
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        with:
            step_status: ${{ needs.pr_title.outputs.status }}
            header: lint-pr-title-error
            message: |
                **Hi there @${{ github.event.pull_request.user.login }}** 👋,

                and **THANK YOU** from the bottom of our hearts for opening this Pull Request! ❤️

                ![Keanu Reeve thumbs up](https://media.giphy.com/media/TJrS7r0f6SOthGTiPe/giphy.gif)

                ----

                In this repository project **we adopted [Conventional Commits specification](https://www.conventionalcommits.org/en/)** to ensure consistency in Git logs.
                We're using the `Squash and merge` strategy once this Pull Request gets reviewed and approved.

                For this reason, **we expect every Pull Request titles _(to the important branches)_ to be semantic**,\
                and looks like the proposed title needs to be adjusted.

                Please don't feel discouraged, and take a look at the error message details below:

                <details>
                  <summary>Error message details</summary>

                  ```
                  ${{ needs.pr_title.outputs.error_message }}
                  ```

                </details>
