# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: PR maintenance

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

permissions:
    pull-requests: write

jobs:
    pr-title:
        name: Validate the Pull Request title
        runs-on: ubuntu-latest
        steps:
            - name: Check if the Pull Request title is semantic
              id: lint_pr_title
              # https://github.com/amannn/action-semantic-pull-request
              uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create error comment
              # When the previous steps fails, the workflow would stop. By adding this
              # condition you can continue the execution with the populated error message.
              if: always() && (steps.lint_pr_title.outputs.error_message != null)
              # https://github.com/marocchino/sticky-pull-request-comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: pr-title-lint-error
                  message: |
                      **Hi there @${{ github.event.pull_request.user.login }}** 👋,

                      and **THANK YOU** from the bottom of our hearts for opening this Pull Request! ❤️

                      ![Keanu Reeve thumbs up](https://media.giphy.com/media/TJrS7r0f6SOthGTiPe/giphy.gif)

                      ----

                      In this repository project **we adopted [Conventional Commits specification](https://www.conventionalcommits.org/en/)** to ensure consistency in Git logs.

                      For this reason, **we expect every Pull Request titles _(to the important branches)_ to be semantic**, and looks like the proposed title needs to be adjusted.\
                      We're using the "Squash and merge" strategy, so what matters the most to us is the title.

                      Please don't feel discouraged, and take a look at the error message below to see the details of error message.

                      ---

                      ```
                      ${{ steps.lint_pr_title.outputs.error_message }}
                      ```

            - name: Delete the error comment
              # Delete a previous comment when the issue has been resolved
              if: ${{ steps.lint_pr_title.outputs.error_message == null }}
              # https://github.com/marocchino/sticky-pull-request-comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: pr-title-lint-error
                  delete: true
