# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: rustfmt

on:
    workflow_call:
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    CI: true
    CARGO_TERM_COLOR: always

permissions:
    pull-requests: write

jobs:
    rustfmt:
        name: rustfmt
        outputs:
            status: ${{ steps.failure.outputs.status || steps.success.outputs.status }}
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - name: Checkout to the repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v4

            - name: Setup Rust
              # https://github.com/dtolnay/rust-toolchain
              uses: dtolnay/rust-toolchain@v1
              with:
                  components: rustfmt
                  toolchain: nightly

            - name: Setup the cache
              # https://github.com/Swatinem/rust-cache
              uses: Swatinem/rust-cache@v2

            - name: Check Rust codebase format with rustfmt
              # https://github.com/mbrobbel/rustfmt-check
              uses: mbrobbel/rustfmt-check@v1
              id: lint_rustfmt
              with:
                  mode: review
                  token: ${{ secrets.GITHUB_TOKEN }}
