# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: tarpaulin

on:
    workflow_call:
        inputs:
            toolchain:
                description: Rust toolchain channel to use
                type: string
                required: false
                default: nightly
    workflow_dispatch:

defaults:
    run:
        shell: bash

env:
    CI: true
    CARGO_TERM_COLOR: always

jobs:
    tarpaulin:
        name: tarpaulin
        outputs:
            status: ${{ steps.failure.outputs.status || steps.success.outputs.status }}
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - name: Checkout to the repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v4

            - name: Setup Rust
              # https://github.com/dtolnay/rust-toolchain
              uses: dtolnay/rust-toolchain@stable
              id: toolchain
              with:
                  components: ""
                  toolchain: ${{ inputs.toolchain }}

            - name: Install cargo extensions binaries
              # https://github.com/taiki-e/install-action
              uses: taiki-e/install-action@v2
              with:
                  tool: cargo-tarpaulin

            - name: Setup the cache
              # https://github.com/Swatinem/rust-cache
              uses: Swatinem/rust-cache@v2
              with:
                  key: ${{ inputs.toolchain }}-${{ steps.toolchain.outputs.cachekey }}-tarpaulin

            - name: Run tarpaulin to generate tests coverage results and upload them to Coveralls.io
              run: >
                  cargo
                  tarpaulin
                  --all-features
                  --coveralls ${{ secrets.COVERALLS_TOKEN }}
                  --no-fail-fast
                  --skip-clean
                  --workspace
